apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-publisher
  namespace: applications
  labels:
    app: rabbitmq-publisher
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: rabbitmq-publisher

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer
  namespace: applications
  labels:
    app: rabbitmq-consumer
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: rabbitmq-consumer
